#!/usr/bin/env python
 
import sys
 
from rqt_car_sensors_rec.car_sensors_rec import CarSensorsRec
from rqt_gui.main import Main
 
plugin = 'rqt_car_sensors_rec'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
