#!/usr/bin/env python

import sys

from rqt_bag_playback.bag import Bag
from rqt_gui.main import Main

plugin = 'rqt_bag_playback.bag.Bag'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Bag.add_arguments))
