#!/usr/bin/env python
 
import sys
 
from rqt_ins_display.ins_display import InsDisplay
from rqt_gui.main import Main
 
plugin = 'rqt_ins_display'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
